# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Build Girders

on:
  schedule:
    - cron: '0 0,1,2,3 * * 5' # schedule multiple times because github does not guarantee a scheduled job to actually run: https://github.community/t/no-assurance-on-scheduled-jobs/133753/2
  release:
    types: [created]

jobs:
  build_girders:
    name: build girders
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11.0.11'
        distribution: 'zulu'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: build girders
      run: |
        mvn --batch-mode clean
        mvn --batch-mode -Ppedantic install
      shell: bash
    - name: upload surefire report
      if: ${{ failure() }}
      uses: actions/upload-artifact@v2
      with:
        name: surefire-reports
        path: girders-demos/girders-demo-test/target/surefire-reports/
    - name: run integration tests
      run: mvn --batch-mode -f girders-demos/girders-demo-test/pom.xml install
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16.0.0'
        distribution: 'zulu'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: run integration tests
      run: mvn --batch-mode -f girders-demos/girders-demo-test/pom.xml install
    
