# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:
    name: build girders
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11.0.11'
        distribution: 'zulu'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: build girders
      run: |
        mvn --batch-mode clean
        mvn --batch-mode --errors --debug -Ppedantic install
      shell: bash
    - name: upload surefire report
      if: ${{ failure() }}
      uses: actions/upload-artifact@v1
      with:
        name: surefire-reports
        path: girders/girders-demos/girders-demo-test/target/surefire-reports/**
