name: Release Girders

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release version'
        required: true
        type: string
      developmentVersion:
        description: 'Development version after release'
        required: true
        type: string
      publishTo:
        description: 'Publish to'
        required: true
        default: 'GitHub & MavenCentral'
        type: choice
        options:
          - 'GitHub'
          - 'MavenCentral'
          - 'GitHub & MavenCentral'
          - 'none (dry run)'

env:
  RELEASE_VERSION: ${{ inputs.releaseVersion }}
  DEVELOPMENT_VERSION: ${{ inputs.developmentVersion }}
  PUBLISH_TO: ${{ inputs.publishTo }}

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Release version: $RELEASE_VERSION"
          echo "Development version: $DEVELOPMENT_VERSION"
          echo "Publish to: $PUBLISH_TO"

  build_release:
    name: build girders release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11.0.11'
        distribution: 'zulu'
        cache: 'maven'
    - name: Maven clean
      run: mvn --batch-mode clean release:clean
      shell: bash
    - name: Maven release:prepare
      run: mvn --batch-mode -DdryRun=${{ env.PUBLISH_TO == 'none (dry run)' }} -DdevelopmentVersion=$DEVELOPMENT_VERSION -DreleaseVersion=$RELEASE_VERSION release:prepare
      shell: bash
    - name: Maven release:perform
      run: mvn --batch-mode -DdryRun=${{ env.PUBLISH_TO == 'none (dry run)' }} release:perform
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}


